### ISSUE TITLE
Previously available function Ship#rotated_by() not longer available

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#46] opened 2024-02-16 22:37 UTC
## Description

Previously available function Ship#rotated_by() is not longer available

## Environment

-   Python version: 3.11.2
-   Operating System: Debian 12 
-   Version of the Python SoCha Client: 2.1.1

## Expected Behavior

Calling the function *Ship#direction.rotated_by(n)* returns a new Direction.

## Actual Behavior

Calling the function *Ship#direction.rotated_by(-1)* leads to an error:

AttributeError: 'builtin_function_or_method' object has no attribute 'rotated_by'

**Comment by maxblan** [comment] 2024-02-17 08:15
This error occurres due to a duplicate caused by adding a method named `direction` to the `Ship` class, which already had an attribute with the same name. A new version will be released on Sunday evening to fix this bug.

**Closed** 2024-02-18 22:38 UTC
Labels: bug
